#!/bin/sh
sleep 3
if command -v python3 >/dev/null 2>&1; then
    # 路径改为 /etc/config/command，匹配files里存放的文件
    if [ -f "/root/scripts/restore_command.py" ] && [ -f "/etc/config/command" ]; then
        python3 /root/scripts/restore_command.py
    fi
fi
exit 0
