name: 上传Release固件到坚果云
on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: 获取并下载最新固件
        run: |
          # 获取下载地址
          DOWNLOAD_URL=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.assets[0].browser_download_url')
          # 获取真实文件名
          FILE_NAME=$(basename "$DOWNLOAD_URL")
          # 下载
          wget -O "$FILE_NAME" "$DOWNLOAD_URL"
          ls -lh
          
      - name: 上传到坚果云根目录
        run: |
          FILE_NAME=$(ls | grep bin | head -1)
          curl -u "${{ secrets.WEBDAV_USERNAME }}:${{ secrets.WEBDAV_PASSWORD }}" \
          -T "$FILE_NAME" \
          "https://dav.jianguoyun.com/dav/$FILE_NAME"
